from pathlib import Path

from selfsuvis.scripts.generate_env import (
    EnvGenerationOptions,
    ResourceProfile,
    build_env_plan,
    render_env,
)


def test_build_env_plan_balanced_profile_uses_expected_sidecars():
    options = EnvGenerationOptions(
        env_name="dev",
        profile="balanced",
        output_path=Path(".env"),
        resources=ResourceProfile(vram_gb=16.0, free_vram_gb=12.0, ram_gb=64.0),
    )

    plan = build_env_plan(options)

    assert plan.selected_backends == {
        "gemma": "ollama",
        "qwen": "ollama",
        "unidrive": "none",
        "reasoning": "ollama",
    }
    assert plan.values["GEMMA_API_MODEL"] == "gemma4:e4b"
    assert plan.values["QWEN_MODEL"] == "qwen2.5vl:7b"
    assert plan.values["UNIDRIVE_ENABLED"] == "false"
    assert plan.values["GPU_TOTAL_GB_HINT"] == "16"
    assert plan.values["GPU_FREE_GB_HINT"] == "12"


def test_build_env_plan_vllm_gemma_maps_model_ids():
    options = EnvGenerationOptions(
        env_name="prod",
        profile="full",
        output_path=Path(".env"),
        resources=ResourceProfile(vram_gb=48.0, free_vram_gb=40.0, ram_gb=128.0),
        gemma_backend="vllm",
    )

    plan = build_env_plan(options)

    assert plan.values["GEMMA_API_BACKEND"] == "vllm"
    assert plan.values["GEMMA_API_MODEL"] == "google/gemma-4-12b-it"
    assert plan.values["GEMMA_API_URL"] == "http://localhost:8000/v1"


def test_build_env_plan_preserves_existing_secrets():
    options = EnvGenerationOptions(
        env_name="dev",
        profile="minimal",
        output_path=Path(".env"),
        resources=ResourceProfile(vram_gb=0.0, free_vram_gb=0.0, ram_gb=32.0),
    )

    plan = build_env_plan(options, existing={"HF_TOKEN": "hf_secret", "API_KEY": "abc123"})

    assert plan.values["HF_TOKEN"] == "hf_secret"
    assert plan.values["API_KEY"] == "abc123"
    assert plan.values["DEVICE"] == "cpu"
    assert plan.values["USE_FP16"] == "false"


def test_render_env_contains_metadata_and_core_keys():
    options = EnvGenerationOptions(
        env_name="dev",
        profile="full",
        output_path=Path(".env"),
        resources=ResourceProfile(vram_gb=24.0, free_vram_gb=20.0, ram_gb=64.0),
    )

    rendered = render_env(build_env_plan(options))

    assert "# Generated by selfsuvis-env" in rendered
    assert "APP_ENV=dev" in rendered
    assert "GEMMA_API_MODEL=gemma4:4b" in rendered
    assert "QWEN_API_URL=http://localhost:11434/v1" in rendered
    assert "QWEN_MODEL=qwen2.5vl:7b" in rendered
    assert "# ss-video" in rendered
    assert "# ss-fusion" in rendered
    assert (
        "FUSION_DATABASE_URL=postgresql://selfsuvis:selfsuvis@localhost:5432/selfsuvis_fusion"
        in rendered
    )
    assert "UNIDRIVE_BACKEND=ollama" in rendered
    assert "SELFSUVIS_USE_GRAPH=1" in rendered
